name: Jira Integration

on:
  push:
    branches:
      - '*'

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Jira issue
        uses: atlassian/gajira-create@v2
        with:
          project: 'SCRUM'
          summary: 'Update from GitHub'
          description: 'This issue is updated from GitHub action'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
